name: Lint
on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
  workflow_dispatch:
  push:
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: pylint --recursive=y ./
